### ISSUE TITLE
TEST Not enough UwU

### ISSUE THREAD

**Issue by sweetinsomniac** [rleong/FoundryVTTAuramancyAlpha#2]
Hey Russell, look. I love you. You know that. But like, **cmon**. You also know our taste has to be matched with this world. Therefore, I vote that at least 40% of the Free Cities be named "Pwincess Mawy OwOington." If not, I will call Wizards of the Coast to cease and desist you until the day you leave this god forsaken planet.

UwU

**Comment by rleong** [comment]
ok
